"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UPDATE_WITH_WHERE_NESTED = exports.UPDATE_MANY_REQUIRED_NESTED = exports.UPDATE_ONE_REQUIRED_NESTED = exports.UPDATE_MANY_NESTED = exports.UPDATE_ONE_NESTED = exports.CREATE_MANY_REQUIRED_NESTED = exports.CREATE_ONE_REQUIRED_NESTED = exports.CREATE_MANY_NESTED = exports.CREATE_ONE_NESTED = exports.WHERE_UNIQUE_INTERFACE = exports.UPDATE_INTERFACE = exports.WHERE_INTERFACE = exports.CREATE_INTERFACE = exports.ORDER_BY = exports.UPDATE = exports.WHERE_UNIQUE = exports.WHERE = exports.CREATE = void 0;
//This is autogenerated types kinds
const CREATE = 'create';
exports.CREATE = CREATE;
const WHERE = 'where';
exports.WHERE = WHERE;
const WHERE_UNIQUE = 'whereUnique';
exports.WHERE_UNIQUE = WHERE_UNIQUE;
const UPDATE = 'update';
exports.UPDATE = UPDATE;
const ORDER_BY = 'orderBy';
exports.ORDER_BY = ORDER_BY;
const CREATE_INTERFACE = 'interfaceCreate';
exports.CREATE_INTERFACE = CREATE_INTERFACE;
const WHERE_INTERFACE = 'interfaceWhere';
exports.WHERE_INTERFACE = WHERE_INTERFACE;
const UPDATE_INTERFACE = 'interfaceUpdate';
exports.UPDATE_INTERFACE = UPDATE_INTERFACE;
const WHERE_UNIQUE_INTERFACE = 'interfaceWhereUnique';
exports.WHERE_UNIQUE_INTERFACE = WHERE_UNIQUE_INTERFACE;
const CREATE_ONE_NESTED = 'createOneNested';
exports.CREATE_ONE_NESTED = CREATE_ONE_NESTED;
const CREATE_MANY_NESTED = 'createManyNested';
exports.CREATE_MANY_NESTED = CREATE_MANY_NESTED;
const CREATE_ONE_REQUIRED_NESTED = 'createOneRequiredNested';
exports.CREATE_ONE_REQUIRED_NESTED = CREATE_ONE_REQUIRED_NESTED;
const CREATE_MANY_REQUIRED_NESTED = 'createManyRequiredNested';
exports.CREATE_MANY_REQUIRED_NESTED = CREATE_MANY_REQUIRED_NESTED;
const UPDATE_ONE_NESTED = 'updateOneNested';
exports.UPDATE_ONE_NESTED = UPDATE_ONE_NESTED;
const UPDATE_MANY_NESTED = 'updateManyNested';
exports.UPDATE_MANY_NESTED = UPDATE_MANY_NESTED;
const UPDATE_ONE_REQUIRED_NESTED = 'updateOneRequiredNested';
exports.UPDATE_ONE_REQUIRED_NESTED = UPDATE_ONE_REQUIRED_NESTED;
const UPDATE_MANY_REQUIRED_NESTED = 'updateManyRequiredNested';
exports.UPDATE_MANY_REQUIRED_NESTED = UPDATE_MANY_REQUIRED_NESTED;
const UPDATE_WITH_WHERE_NESTED = 'updateWithWhereNested';
exports.UPDATE_WITH_WHERE_NESTED = UPDATE_WITH_WHERE_NESTED;